# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "samRobot"
  fleet_manager:
    ip: "127.0.0.1"
    port: 7878
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.22, 2.5] # velocity, acceleration
    angular: [2.84, 3.2] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.22 # radius in m
    vicinity: 0.42 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.9 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "charge" # [park, charge, nothing]

# TinyRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for tinyRobot1
  robot_1:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "start"
        orientation: 0.0 # radians
      charger:
        waypoint: "start"
  # Configuration for tinyRobot2
  # robot_1:
  #   robot_config:
  #     max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
  #   rmf_config:
  #     robot_state_update_frequency: 10.0
  #     start:
  #       map_name: "L1"
  #       waypoint: "start"
  #       orientation: 0.0 # radians
  #     charger:
  #       waypoint: "start"

reference_coordinates:
  rmf: [[5.067, -2.493], [7.569, -2.493], [2.674, -1.768], [1.088, -3.490]]
  robot: [[0.0, 0.0], [2.471907754993206, -0.01072292922208354], [-2.8754609185919446, 0.9093762972365813], [-4.560408549388617, -1.3273243797069398]]