# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "samRobot"
  fleet_manager:
    ip: "127.0.0.1"
    port: 7878
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.22, 2.5] # velocity, acceleration
    angular: [2.84, 3.2] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.1435 # radius in m
    vicinity: 0.16 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.9 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "park" # [park, charge, nothing]

# TinyRobot CONFIG =================================================================

robots:
  robot_1:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "start_1"
        orientation: 0.0 # radians
      charger:
        waypoint: "start_1"
  
  robot_2:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "start_2"
        orientation: 0.0 # radians
      charger:
        waypoint: "start_2"

reference_coordinates:
  rmf: [[7.8044, -10.7495], [4.0249, -11.4367], [9.7678, -8.001], [4.3837, -4.6246]]
  robot: [[0.0, 0.0], [-3.866, -0.9017], [2.0126, 2.5254], [-3.2517, 6.3645]]